theme = "tale-hugo"
title = "Decolonial AI Community" 



[menu]

  [[menu.main]]
  identifier = "learning"
  name = "Resources"
  title = "Resources-title"
  url = "/resources"
  weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    title = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About" # shows up in menu
    title = "About-title" # shows up where?
    url = "/about"
    weight = 30




# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
